#!/usr/bin/env python3
"""Generate the register appendix from the machine's own headers.

Chapter 10 promises this: "the authoritative register-level reference is
core/io.h in the source tree; this chapter will be generated from it, the
way the Neo6502 handbook generates its keyword reference from the firmware
source."  This is that generator.

It takes every top-level block comment in the headers below that documents
registers -- the test is a line mentioning a $XX offset -- strips the
comment furniture, and emits it verbatim.  Verbatim on purpose: those
comments are the reference the machine is written against, and anything
this script rewrote could drift from them.  Adding a device to a header
adds it to the book; nothing here needs editing for that.

Run by make-guide.sh.  Output: generated/registers.tex (never edit).
"""
import re, sys, pathlib

HEADERS = [
    ("core/io.h",    "The I/O page"),
    ("core/vicky.h", "VICKY, SHEILA and the sprites"),
    ("core/net.h",   "The network"),
    ("core/term.h",  "JIM, the terminal"),
    ("core/mem.h",   "Memory and the far view"),
]

# Nicer titles than the comment's own first line, where the first line is
# a sentence rather than a name.  Matched by prefix.
TITLES = {
    "K4510 I/O page":      "The page map",
    "BANK registers":      "Bank registers and the far gate",
    "MATH unit":           "The MATH unit",
    "SYS registers":       "System registers, and the SIDs",
    "Keyboard":            "The keyboard",
    "Names are NUL":       "Storage: the host filesystem",
    "All addresses phys":  "The DMA engine",
    "The Tube":            "The Tube",
    "VICKY --":            "VICKY",
    "The network, three":  "The N: device",
    "JIM,":                "JIM",
    "The ROM image":       "The ROM window and the stub page",
    "$D000-":              "The page map",
}

BLOCK = re.compile(r"/\*(.*?)\*/", re.S)
REGISTER_LINE = re.compile(r"\$[0-9A-Fa-f]{2,4}")

def clean(block):
    out = []
    for line in block.split("\n"):
        line = re.sub(r"^\s*\*ic? ?", "", line)      # " * " and " *" furniture
        line = re.sub(r"^\s*\* ?", "", line)
        out.append(line.rstrip())
    while out and not out[0].strip():  out.pop(0)
    while out and not out[-1].strip(): out.pop()
    # drop the common indent that the comment furniture left behind
    body = [l for l in out if l.strip()]
    pad = min((len(l) - len(l.lstrip()) for l in body), default=0)
    return [l[pad:] if l.strip() else "" for l in out]

WIDTH = 76

def fold(lines):
    """A5 is narrow and these tables are wide: fold at a space, and indent the
    continuation past the register column so the fold reads as a fold."""
    out = []
    for line in lines:
        indent = " " * (len(line) - len(line.lstrip()) + 4)   # once, per source line
        while len(line) > WIDTH:
            cut = line.rfind(" ", 0, WIDTH)
            if cut <= len(indent):
                break
            out.append(line[:cut])
            line = indent + line[cut + 1:].lstrip()
        out.append(line)
    return out

def tex(t):
    for a, b in [("\\", "/"), ("&", "\\&"), ("%", "\\%"), ("$", "\\$"),
                 ("#", "\\#"), ("_", "\\_"), ("{", "\\{"), ("}", "\\}"),
                 ("~", "\\textasciitilde{}"), ("^", "\\textasciicircum{}")]:
        t = t.replace(a, b)
    return t

def title_for(first_line):
    first_line = first_line.strip()
    for prefix, name in TITLES.items():
        if first_line.startswith(prefix):
            return name
    return first_line.rstrip(".:").split("--")[0].strip()

def main():
    root = pathlib.Path(__file__).resolve().parents[2]
    out = ["% GENERATED by doc/guide/mkregs.py -- do not edit.",
           "% Source: the register comments in the machine's own headers.", ""]
    widest, count = 0, 0
    for rel, part in HEADERS:
        src = (root / rel).read_text()
        blocks = [clean(b) for b in BLOCK.findall(src)]
        blocks = [b for b in blocks if b and sum(bool(REGISTER_LINE.search(l)) for l in b) >= 2]
        if not blocks:
            continue
        out.append("\\section{%s}" % part)
        out.append("\\noindent Generated from \\pth{%s}.\\par\\medskip" % rel)
        for b in blocks:
            count += 1
            head, b = b[0], fold(b)
            widest = max(widest, max(len(l) for l in b))
            out.append("\\subsection*{%s}" % tex(title_for(head)))
            out.append("\\begin{Verbatim}[fontsize=\\footnotesize,samepage=false]")
            out.extend(b)
            out.append("\\end{Verbatim}")
        out.append("")
    (pathlib.Path(__file__).parent / "generated").mkdir(exist_ok=True)
    (pathlib.Path(__file__).parent / "generated" / "registers.tex").write_text("\n".join(out) + "\n")
    print("registers: %d blocks, widest line %d chars" % (count, widest))
    if widest > 78:
        print("registers: WARNING -- %d chars will run off an A5 page at footnotesize" % widest,
              file=sys.stderr)
        return 1
    return 0

sys.exit(main())
