#!/bin/sh
# Lay out an SD card for the BMC-K4510: firmware + kernel8.img at the root,
# the machine's files under /k4510.  Usage: pi/make-sd.sh /path/to/mounted/card
set -e
M="$1"; [ -d "$M" ] || { echo "usage: $0 /mounted/card"; exit 1; }
HERE=$(cd "$(dirname "$0")" && pwd); REPO=$(cd "$HERE/.." && pwd)
B="${SHIM:-$HOME/Projects/k4510-pi/circle-libsdl2}/circle-stdlib-rpi3/libs/circle/boot"
cp "$B/bootcode.bin" "$B/start.elf" "$B/fixup.dat" "$M/"
cp "$HERE/config.txt" "$M/config.txt"
cp "$HERE/kernel8.img" "$M/kernel8.img"
mkdir -p "$M/k4510/rom" "$M/k4510/data" "$M/k4510/fs"
cp "$REPO/rom/kernal.bin" "$REPO/rom/wozmon.bin" "$REPO/rom/demo.bin" "$M/k4510/rom/"
cp "$REPO/data/font8.bin" "$M/k4510/data/"
cp -rL "$REPO"/fs/* "$M/k4510/fs/"   # -L: fs/SID is a symlink; FAT32 needs real files
cp "$REPO/basic/README-EhBASIC.txt" "$M/k4510/"

# The card says what it is and which build it carries.  core/build.h is
# generated by the build, so the stamp cannot drift from the kernel.
cp "$HERE/README-SD.txt" "$M/README.txt"
if [ -f "$REPO/core/build.h" ]; then
    STAMP=$(sed -n 's/.*K4510_BUILD "\(.*\)".*/\1/p' "$REPO/core/build.h")
    [ -n "$STAMP" ] && printf '\nTHIS CARD\n  Build %s, laid out %s.\n' \
        "$STAMP" "$(date +%Y-%m-%d)" >> "$M/README.txt"
fi
sync
echo "card ready:"; ls -R "$M" | head -40
