#!/usr/bin/env python3
"""Bomb Party -> VICKY: data/bombparty/bomb_party_v4.png -> demo/bomber.h

The sheet is 15x19 cells of 16x16 (CC-BY 3.0, see data/bombparty/
VENDORED-FROM.txt).  This picks the cells BOMBER uses, composites the
see-through ones (bombs, blasts, pickups) over the grass so they can be
opaque layer-0 tiles, palettizes everything into VICKY indices 32 and up
(the console keeps 0-15), and writes one C header:

    bp_pal[][3]            the palette, index 32 first
    bp_tiles[N_TILE*256]   FLOOR WALL BOX BOMB0 BOMB1 BOMB2
                           BLASTC BLASTH BLASTV PUB PUF   (8 bpp, 16x16)
    bp_spr[N_SPR*256]      hero D0 D1 S0 S1 U0 U1, green D0 D1,
                           blue D0 D1, purple D0 D1       (0 = transparent)
"""
import os
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "data", "bombparty", "bomb_party_v4.png")
OUT = os.path.join(HERE, "..", "demo", "bomber.h")
im = Image.open(SRC).convert("RGBA")

def cell(cx, cy):
    return im.crop((cx * 16, cy * 16, cx * 16 + 16, cy * 16 + 16))

BASE = 32
pal = {}                                 # rgb -> global palette index
def idx(px):
    if px[3] < 128: return 0
    rgb = px[:3]
    if rgb not in pal: pal[rgb] = BASE + len(pal)
    return pal[rgb]

FLOOR = cell(2, 13)
def over_floor(c):
    o = FLOOR.copy(); o.paste(c, (0, 0), c); return o

TILES = [("FLOOR",  FLOOR),
         ("WALL",   cell(0, 12)),
         ("BOX",    cell(9, 13)),
         ("BOMB0",  over_floor(cell(4, 18))),
         ("BOMB1",  over_floor(cell(5, 18))),
         ("BOMB2",  over_floor(cell(8, 18))),
         ("BLASTC", over_floor(cell(1, 18))),
         ("BLASTH", over_floor(cell(0, 18))),
         ("BLASTV", over_floor(cell(14, 14))),
         ("PUB",    over_floor(cell(11, 15))),
         ("PUF",    over_floor(cell(14, 17)))]
SPR = [cell(c, r) for r, cols in ((17, (0, 2, 4, 6, 8, 9)),   # the hero
                                  (14, (0, 2)),               # green
                                  (15, (0, 2)),               # blue
                                  (16, (0, 2)))               # purple
       for c in cols]

def blob(cells, opaque):
    out = bytearray()
    for c in cells:
        for px in c.getdata():
            i = idx(px)
            if opaque and i == 0: i = idx((0, 0, 0, 255))    # tiles have no holes
            out.append(i)
    return out

tiles = blob([t[1] for t in TILES], True)
spr = blob(SPR, False)
assert BASE + len(pal) <= 255, len(pal)

def carray(name, data):
    rows = []
    for i in range(0, len(data), 16):
        rows.append("    " + ",".join(str(b) for b in data[i:i+16]) + ",")
    return f"static const uint8_t {name}[{len(data)}] = {{\n" + "\n".join(rows) + "\n};\n"

with open(OUT, "w") as f:
    f.write("/* generated by tools/mkbomber.py from data/bombparty/ -- do not edit.\n")
    f.write(" * Bomb Party by devurandom, richtaur and cemkalyoncu, CC-BY 3.0. */\n")
    f.write(f"#define BP_BASE {BASE}\n#define BP_NPAL {len(pal)}\n")
    f.write(f"#define BP_NTILE {len(TILES)}\n#define BP_NSPR {len(SPR)}\n")
    for i, (name, _) in enumerate(TILES):
        f.write(f"#define BT_{name} {i}\n")
    p = sorted(pal.items(), key=lambda kv: kv[1])
    f.write(carray("bp_pal", [v for rgb, _ in p for v in rgb]))
    f.write(carray("bp_tiles", tiles))
    f.write(carray("bp_spr", spr))
print(f"bomber.h: {len(pal)} colours, {len(TILES)} tiles, {len(SPR)} sprite frames")
