#!/usr/bin/env python3
"""Kenney's Tiny Dungeon -> VICKY: data/tinydungeon/ -> demo/tiny.bin + demo/tiny.h

tiny.bin, loaded by the K4SG header at TINY_PHYS:
   +0            tiles: 132 x 16x16 at 8 bpp, 256 bytes each, one row per 16
                 bytes, pixel = palette index (0 = transparent). A 16x16 8 bpp
                 sprite has the same layout, so sprite DATA points here too.
   +TINY_MAP     the map: MAPW x MAPH entries, 2 bytes each -- bits 0-9 tile,
                 bit 10 H-flip, bit 11 V-flip -- the Tiled sample map tiled 2x2.
tiny.h: the palette (RGB, index 1..N), the sizes, and walkable[] -- one
byte per tile, 1 where a character may stand (floor: few colours, no wall
edge), found by looking rather than by hand.
"""
import os, re, sys, struct
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "data", "tinydungeon")
OUT = os.path.join(HERE, "..", "demo")
TW = TH = 16; GUT = 0                    # the _packed sheet has no gutters
COLS, ROWS = 12, 11; NT = COLS * ROWS
REP = 2                                  # the 32x20 sample map, tiled REP x REP

im = Image.open(os.path.join(SRC, "tilemap_packed.png")).convert("RGBA")
pal = {}                                 # rgb -> index, 0 kept for transparent
def idx(px):
    if px[3] < 128: return 0
    rgb = px[:3]
    if rgb not in pal: pal[rgb] = len(pal) + 1
    return pal[rgb]

tiles = bytearray(); ncol = []
for t in range(NT):
    r, c = divmod(t, COLS)
    x0, y0 = c * (TW + GUT), r * (TH + GUT)
    seen = set()
    for y in range(TH):
        for x in range(TW):
            i = idx(im.getpixel((x0 + x, y0 + y))); tiles.append(i); seen.add(i)
    ncol.append(seen)
assert len(pal) < 255, len(pal)

# walkable: the floor tiles. A floor is more than half one colour, and that
# colour is one of the two the sheet's plain floors are made of (tile 0,
# the dark brown; tile 48, the sand) -- so a cracked or pebbled floor counts
# and a grey wall of the same flatness does not.
from collections import Counter
def dominant(t):
    c = Counter(tiles[t * 256:(t + 1) * 256]).most_common(1)[0]; return c[0], c[1] / 256.0
floor_cols = {dominant(0)[0], dominant(48)[0]}
walk = bytearray(NT)
for t in range(NT):
    col, frac = dominant(t)
    if col in floor_cols and frac >= 0.55: walk[t] = 1
walk[52] = 1                                         # the big-pebble sand: mostly pebbles
walk[43] = walk[44] = 0                              # the two plinths: sand under a statue

tmx = open(os.path.join(SRC, "sampleMap.tmx")).read()
w = int(re.search(r'<map[^>]*\swidth="(\d+)"', tmx).group(1))
h = int(re.search(r'<map[^>]*\sheight="(\d+)"', tmx).group(1))
csv = re.search(r'<data encoding="csv">(.*?)</data>', tmx, re.S).group(1)
gids = [int(v) for v in csv.replace("\n", "").split(",") if v.strip()]
assert len(gids) == w * h
def ent(g):
    hf, vf = bool(g & 0x80000000), bool(g & 0x40000000)
    if g & 0x20000000: hf, vf = vf, hf              # a diagonal flip: nearest we have
    i = (g & 0x0FFFFFFF) - 1
    if i < 0: i = 0
    return i | (0x400 if hf else 0) | (0x800 if vf else 0)
MAPW, MAPH = w * REP, h * REP
mp = bytearray()
for y in range(MAPH):
    for x in range(MAPW):
        mp += struct.pack("<H", ent(gids[(y % h) * w + (x % w)]))

bin_ = bytes(tiles) + bytes(mp)
open(os.path.join(OUT, "tiny.bin"), "wb").write(bin_)
with open(os.path.join(OUT, "tiny.h"), "w") as f:
    f.write("/* generated by tools/mktiny.py from data/tinydungeon -- do not edit */\n")
    f.write(f"#define TINY_NTILES {NT}\n#define TINY_MAP {len(tiles)}UL\n")
    f.write(f"#define TINY_MAPW {MAPW}\n#define TINY_MAPH {MAPH}\n#define TINY_NCOL {len(pal)}\n")
    f.write("static const uint8_t tiny_pal[TINY_NCOL][3] = {")
    f.write(",".join("{%d,%d,%d}" % rgb for rgb, _ in sorted(pal.items(), key=lambda kv: kv[1])))
    f.write("};\nstatic const uint8_t walkable[TINY_NTILES] = {")
    f.write(",".join(str(b) for b in walk)); f.write("};\n")
print(f"tiny.bin: {len(tiles)} tile bytes + {len(mp)} map bytes = {len(bin_)}; {len(pal)} colours; walkable: {[t for t in range(NT) if walk[t]]}")
